// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260713094430_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backend.Models.Chair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChairNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OccupiedSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Chairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChairNumber = "Chair 1",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 2,
                            ChairNumber = "Chair 2",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 3,
                            ChairNumber = "Chair 3",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 4,
                            ChairNumber = "Chair 4",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 5,
                            ChairNumber = "Chair 5",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 6,
                            ChairNumber = "Chair 6",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 7,
                            ChairNumber = "Chair 7",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 8,
                            ChairNumber = "Chair 8",
                            IsOccupied = false
                        },
                        new
                        {
                            Id = 9,
                            ChairNumber = "Chair 9",
                            IsOccupied = false
                        });
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChairId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChairId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Backend.Models.Customer", b =>
                {
                    b.HasOne("Backend.Models.Chair", "Chair")
                        .WithMany()
                        .HasForeignKey("ChairId");

                    b.Navigation("Chair");
                });
#pragma warning restore 612, 618
        }
    }
}
